### ISSUE TITLE
Add Id library plugin as a dependancy for newer versions

### ISSUE THREAD

**Issue by TheHappyHopper** [eirikh1996/Movecraft#115]
The plugin currently doesn't work in newer versions and needs a rewrite for 1.13.2+ due to using numerical id's

**Describe the solution you'd like**
Add ID Library as a dependency to movecraft, I have already tested movecraft with this plugin enabled and it works flawlessly with no issues in 1.16.5, doing this will at least give the author some breathing room while the plugin is updated slowly but surely

ID Library on spigotmc > https://www.spigotmc.org/resources/id-library-old-id-support-lib-new-minecraft-ids-1-13-x-1-16-x.62124/

**Comment by TomLewis** [comment]
Alternatively https://www.spigotmc.org/resources/id-converter.52099/
Convert your files.
