### ISSUE TITLE
Latest release is missing the .jar

### ISSUE THREAD

**Issue by UAVwaffle** [eirikh1996/Movecraft#123]
The latest release is missing the .jar, I don't know if that was or purpose or not, just thought I'd mention it. I never could get the source to compile right for me :/

**Comment by UAVwaffle** [comment]
Does anyone know how to export this mod from source, I don't know much on the subject and what it says to do in the "read me" file doesn't seem to work

**Comment by ConaII** [comment]
https://github.com/ConaII/Movecraft/releases
