### ISSUE TITLE
How do I build the latest version from source, you didn't upload a .jar

### ISSUE THREAD

**Issue by UAVwaffle** [eirikh1996/Movecraft#124]
Currently movecraft isn't compatible with with world-height datapacks, the latest version say's it fixed that, but I can't use it because no .jar is provided.  I tried building it, but nothing I do seems to work.  Does anyone know how to build this?  And yes, I did follow the instructions on the front page, I'm just not very experienced so I'm probably doing something wrong idk

**Comment by ConaII** [comment]
I can build it for ya.
And explain it to you
If you still need this.

**Comment by UAVwaffle** [comment]
Both would be good, Thanks! (sorry for late reply, I missed the notification)

**Comment by ConaII** [comment]
Nice!
Um, I'm coming back from school right now.
Would you like to contact me via Discord?
I can help you with other things too

**Comment by UAVwaffle** [comment]
Ya discord works for me, but I'm a bit busy rn.  I could probs do it in an hour or two

**Comment by ConaII** [comment]
You say

**Comment by ConaII** [comment]
Send me your discord

**Comment by UAVwaffle** [comment]
Ah sorry, the thing I was working on took way longer than it should to fix, I'll throw my discord here so we can get the dm started, but I can't work on it today, maybe tom, definitely Friday.  UAVwaffle#1369

**Comment by ConaII** [comment]
I've made a windows script to build the necessary jars for this.

https://github.com/ConaII/SpigotAutoBuilder/blob/main/AutoBuilder.bat
https://github.com/ConaII/SpigotAutoBuilder/releases/latest

**Comment by ConaII** [comment]
java -jar BuildTools.jar --rev 1.17 --output-dir ./product --remapped
IS, ABSOLUTELY NEEDED for dependency 1_17

**Comment by ConaII** [comment]
https://github.com/ConaII/Movecraft/releases

**Comment by ConaII** [comment]
Btw, might be worth trying beta 4.0 of movecraft
https://github.com/APDevTeam/Movecraft/releases/

**Comment by UAVwaffle** [comment]
It is resolved, *note movecraft 8.0 at the time of writing isn't compatible with world height datapacks
