### ISSUE TITLE
Pilot Stick not working in latest and older development builds

### ISSUE THREAD

**Issue by AlcoRS11** [eirikh1996/Movecraft#14]
**The Issue:**
When using the PilotTool (configured as a stick), right clicking does not make the craft move forward or in the desired direction and left-clicking does not enable the Direct Control mode. It seems the stick is broken. This issue was noted on PaperSpigot 1.13.2. Older builds of the plugin compatible with this version also yielded the same results. I even attempted to use other items such as a carrot or blaze rod and the same effect of no movement was observed. **No logs were printed into the console regarding this error.**

**Expected behavior:**
Clicking the stick should make the craft move or if left-clicking, enable direct control mode.

**Version affected:**
 - Movecraft: 7.0.0 for 1.10 - 1.14.4 Beta 1 HOTFIX 2

**Comment by RyanA3** [comment]
I'm having the same issue on spigot 1.14.4
Changing the item id to a different item id, or to a 1.13.2+ "material" did not fix it.

**Comment by eirikh1996** [comment]
fixed in cb09b08c24a76c7a76160341333a02b5c28522c5
