### ISSUE TITLE
[1.14.4] Movecraft doesn't generate .craft files with proper material names

### ISSUE THREAD

**Issue by RyanA3** [eirikh1996/Movecraft#15]
**Describe the bug**
On a fresh start of Movecraft, it creates new .craft files for all the types of crafts. It does not recognize some of the materials in the .craft files that it generates. For example: "redstone_repeater" and "enchantment_table" makes the plugin error out on startup (IllegalArgumentException.) Replacing the inproper materials with their correct 1.14.4 names fixes the problem.

**To Reproduce**
Load a fresh start of movecraft in 1.14.4

**Expected behavior**
.craft files are generated with the correct 1.14.4 material names that Movecraft recognizes upon loading them

**Versions (please complete the following information):**
 - Movecraft: [Latest Hotfix as of 10-25-19]
 - Minecraft [1.14.4]
 - PaperSpigot [v221 - 1.14.4]

**Additional Context**
Log file <3
[latest.log](https://github.com/eirikh1996/Movecraft/files/3774004/latest.log)

**Comment by AlcoRS11** [comment]
I had this same bug a well. I ended up finding the proper item names on the internet and checked what isn't right. Some of the material names were outdated. 3 Items were the issue: player_head (was SKULL), ender_chest (was something like "ender chest") and enchantment table (should be "enchanting_table", NOT "enchantment_table" or similar) Just go edit the craft files and ctrl+f the entries and replace the damaged values.
