### ISSUE TITLE
[1.14.4] Failure to collapse craft hitboxes (torpedos)

### ISSUE THREAD

**Issue by RyanA3** [eirikh1996/Movecraft#16]
**Describe the bug**
Letting a craft cruise into unloaded chunks will result in this madness in the console 
![Capture](https://user-images.githubusercontent.com/32079801/67809762-b5cdfb80-fa6f-11e9-9ccc-b04ac8e7ff05.PNG)

**Expected behavior**
Movecraft should time out after too many attempts at collapsing ship hitboxes, or know to treat this as a ship running into unloaded chunks.

**Versions (please complete the following information):**
 - Movecraft: [Most Recent Hotfix]
 - Minecraft [e.g. 1.14.4]
 - PaperSpigot [221]

**Comment by Techwolf77** [comment]
It does the same on our server, we have a range of about 3 chunks before we just call them duds, but get the same error the entire flight which is until it flys off the map

**Comment by eirikh1996** [comment]
Is the chunk it enters loaded?
