### ISSUE TITLE
Radio Sign

### ISSUE THREAD

**Issue by GalacticCraft** [eirikh1996/Movecraft#2]
**Describe the feature you'd like**
A sign that allows communications between ships that are or are not being piloted. The sign would have the option of switching between 999 different channels. The user would right click the sign to change the number, and shift right click the sign to choose which number to change. They would also be able to set the channel with a command, such as "/radio 983" which would set their channel to 983. Anyone within 30 blocks of the radio sign would be able to hear it if the radio itself is set to a channel that has another radio sign communicating in from, opposed to having to currently be piloting a craft. It wouldn't rely on multiple users all having to have radios set to the same frequency. It relies on two radios, each having the same frequency, with any number of users communicating from both sides.

**Additional context**
The sign would look like this:
(Example)
Radio:
9-8-3
^----
(The arrow would be the number currently being changed if right clicked. Shift right clicking will change which number you want to set.)
Radio:
9-8-3
--^--

**Comment by Steffbeard** [comment]
you can do this through other plugins (and much better executed and usable), I don't see the reason for adding this feature besides for the aesthetic

**Comment by GalacticCraft** [comment]
Are they specifically compatible with Movecraft for 1.13.2? If so, link them to me.

**Comment by GalacticCraft** [comment]
> 
> 
> you can do this through other plugins (and much better executed and usable), I don't see the reason for adding this feature besides for the aesthetic

So I've looked around for other Movecraft radios specifically for 1.13.2 and higher, and I've found nothing. Since you haven't linked me to any addons that fit the description of this suggestion and no one else has made an argument against this, I'm going to consider this suggestion valid.

**Comment by Steffbeard** [comment]
Reread what I said. I never said it's for Movecraft. The reason no one made it for Movecraft is because it's pointless to specifically code a single purpose mechanic that serves no purpose for 99% of the user base, when you can use an alternative plugin that adds way more customizability and more features than you would ever need such as HeroChat or similar.

**Comment by GalacticCraft** [comment]
> 
> 
> Reread what I said. I never said it's for Movecraft. The reason no one made it for Movecraft is because it's pointless to specifically code a single purpose mechanic that serves no purpose for 99% of the user base, when you can use an alternative plugin that adds way more customizability and more features than you would ever need such as HeroChat or similar.

This is in no way pointless. The goal of this plugin is to have ship-to-ship communication via specific channels. HeroChat and other plugins are nice, but they're not as specific as my idea is.
