### ISSUE TITLE
Redstone Devices and Circuitry not working when craft is piloted or otherwise moves. [1.13.2-1.14.x]

### ISSUE THREAD

**Issue by AlcoRS11** [eirikh1996/Movecraft#21]
**The Bug:**
When piloting an aircraft or vehicle with the plugin, all redstone circuitry does not work (e.g dispensers not firing when switched on) and even after the craft is released, the redstone does not work.

**To Reproduce**
1. Build an aircraft with redstone weaponry (dispensers will do)
2. Pilot the aircraft and move it.
3. Try and turn the circuit on and see that it does not work.
4. Release craft and try redstone again to see it does not work.

**Expected behavior**
Redstone is supposed to work even if craft is moved in any way.

**Discovered bug using:**
 - Movecraft: 7.0.0 Beta 2
 - Java 8
 - Minecraft v1.13.2

**Comment by eirikh1996** [comment]
Did you use the most recent download?

**Comment by AlcoRS11** [comment]
I di. I sibsequeny updated the plugin, hoping it o

**Comment by AlcoRS11** [comment]
ok

**Comment by eirikh1996** [comment]
Does this happen on versions 1.12.2 and below or only on 1.13+?

**Comment by eirikh1996** [comment]
Can confirm this problem does not exist in upstream
