### ISSUE TITLE
Players not moving with the craft during cruise.

### ISSUE THREAD

**Issue by Galithas** [eirikh1996/Movecraft#22]
**Context**
I'm a little new to this plugin / I'm dim so please be patient

**Problem**
Using the /cruise function causes players to fly off the vehicle.

**Steps to reproduce the behavior:**
1. Use the latest build
2. Use default craft types
3. Use /cruise 

**Expected behavior**
I expected players to be teleported along with the craft as it cruises and not stay in the same place,  causing them to fall.

**Versions**
 - Movecraft 7.0.0 beta 3 HOTFIX 1
 - Java version: ¯\_(ツ)_/¯
 - Minecraft 1.14.4

**Comment by galacticwarrior9** [comment]
Can confirm on 1.13.2 as well.

**Comment by eirikh1996** [comment]
Does this happen if the server is lagging or under normal conditions as well?

**Comment by eirikh1996** [comment]
Seems like a side effect of the lagg, which was fixed in 725e799f40b9c3d11cbabeb5f87f0ae23818fe4b. Tested after fixing the performance problem in #23 and the problem was nonexistent after
