### ISSUE TITLE
Performance regression in a build after Beta 2

### ISSUE THREAD

**Issue by galacticwarrior9** [eirikh1996/Movecraft#23]
I have noticed that there has been a substantial performance regression sometime after the release of Beta 2. See this [Timings report](https://timings.aikar.co/?id=72fbc463f30d460491c35d451ce0d94f), for example. Move the slider under the graph so only the last time segment is viewed - you will find that AsyncManager takes up 24.65% of the tick. I should note that while a ship around 4000 blocks large was cruising during this segment on Beta 2 I generally found 10% of the tick would be taken at maximum with similar sized ships moving.

**Comment by eirikh1996** [comment]
Could be the waterlogging part that causes drop in performance. That feature is new to the recent release of my Movecraft fork. It scans EVERY ship on the server in search for blocks to waterlog.
