### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by GrandpaBlackTF2** [eirikh1996/Movecraft#24]
I found the type files and the actual Movecraft folder in the downloads, but I'm wondering where the actual .jar is for the plugin? I can't find it in any of the files on the branches, some help would be appreciated. My server version is 1.13, if that makes any difference. Thanks.

**Comment by eirikh1996** [comment]
They are under the releases tab under code: https://github.com/eirikh1996/Movecraft/releases

Note that the plugin is still in beta, meaning that bugs are present
