### ISSUE TITLE
Movecraft not loading properly

### ISSUE THREAD

**Issue by GrandpaBlackTF2** [eirikh1996/Movecraft#27]
Movecraft isn't loading properly in console.

1. Start server
2. Check log
3. Test ingame
4. Doesn't work

**Expected behavior**
Ships (and other types) to load properly and work, however, they do not, typing [Helm] on signs doesn't do anything, and ships are unable to be piloted at all, without any feedback ingame or in console.

Screenshots:
[https://imgur.com/a/GPQbFtp](url)

 - Movecraft 7.0 for 1.13+ Release candidate 1, 7.0 for 1.10 - 1.14.4 Beta 3 HOTFIX 2
 - Minecraft 1.13.2

A full, clean reinstall still has not fixed the problem.

**Comment by eirikh1996** [comment]
Try this version: https://github.com/eirikh1996/Movecraft/releases/tag/Movecraft_7.0_for_1.10_to_1.14.4_beta_4

**Comment by GrandpaBlackTF2** [comment]
I tried with the updated version, but the error logs are the exact same, even after a complete, clean reinstall
