### ISSUE TITLE
Cruise signs are broken in 1.15 +

### ISSUE THREAD

**Issue by Jokkaj** [eirikh1996/Movecraft#30]
Cruise signs are broken in 1.15 +.
They work properly in other versions of the game.
In 1.15 they seem to ignore the speed variable in the .craft file and make the ship super fast and buggy, here a short video:
https://youtu.be/IFq5eChbaww

The speed value is the default 0.5 in the configs.
You can download the configs that I am currently using here:
https://www.dropbox.com/s/x4eipjq7rms1zz5/Movecraft.zip?dl=0

I used the same configs with the latest version of the plugin (beta 8)

**Comment by eirikh1996** [comment]
Which flag are you using? speed or cruiseSpeed?

**Comment by Jokkaj** [comment]
> Which flag are you using? speed or cruiseSpeed?

Speed 
I have it on 0.5

**Comment by Jokkaj** [comment]
> Which flag are you using? speed or cruiseSpeed?

I found a solution to the problem, you just need to add "cruiseSpeed: 0.5" in the .craft config under "speed" because it is missing when the plugin generate those configs

![IMG_20200124_224051_929](https://user-images.githubusercontent.com/58168823/73105990-958ccc00-3efa-11ea-9529-05e98be21728.jpg)
