### ISSUE TITLE
Movecraft 7.0 for 1.9.4 - 1.14.4 Beta 9 Insufficient Permissions for non-op'd players

### ISSUE THREAD

**Issue by icekoob** [eirikh1996/Movecraft#31]
Players who are not op'd are unable to use movecraft commands such as ./pilot and are unable to pilot vehicles even though requirecreateperm is set to false.

**To Reproduce**
1. I have essentialsx as a permissions plugin
2. 1.15.2 server
3. Paper
4. don't be op'd and attempt to use any movecraft command results in the message "insufficient permissions"

**Expected behavior**
Expecting functionality of movecraft for un-opped players w/ default config.

**Versions (please complete the following information):**
 - Movecraft 7.0 for 1.9.4 - 1.14.4 Beta 9
 - Java [e.g. JDK 8.0.1]
 - Minecraft 1.15.2

**Comment by eirikh1996** [comment]
Players must have the movecraft.<type name>.pilot permission in order to pilot. RequireCreatePerm only regulates requiring permission movecraft.<type name>.create for players to PLACE craft signs. So this is intended behaviour and not a bug
