### ISSUE TITLE
Kelp, damn kelp everywhere

### ISSUE THREAD

**Issue by CalamityGreen** [eirikh1996/Movecraft#33]
Hello. Can i request option to break some sort of blocks on the way? (or just kelp).

Another usage - mining machines which are can break stone and ores blocks.

**Comment by Steffbeard** [comment]
This either used to be a feature or still is. The config option "HarvestBlocks" is probably what you are looking for. 

https://github.com/APDevTeam/Movecraft/wiki/Example-Craft-File#advanced-options

**Comment by CalamityGreen** [comment]
Im added

`harvestBlocks:`
`    - KELP_PLANT`
`    - KELP`

but ships are still obstructed with kelp (The craft cannot move because its patch is obstructed! @ x,y,z,KELP)

**Comment by eirikh1996** [comment]
@CalamityGreen You need to define harvesterBladeBlocks too. These blocks will act as a harvester blade that harvests the block
