### ISSUE TITLE
Entities won't stay on crafts (Paper 1.15.2)

### ISSUE THREAD

**Issue by Jokkaj** [eirikh1996/Movecraft#35]
They just stay where they are, they don't move with the craft, this is a problem because ships can't move item frames, paintings, armorstands, animals and this breaks all chairs plugin (being able to sit and relax while moving would be pretty cool).
This used to work on older versions of this plugin? I don't remember.

**Comment by cccm5** [comment]
This is a config option that was added recently, and did not use to work. Set `onlyMovePlayers` to false in the craft files you want to move non-player entities.

**Comment by Scarecrow-01** [comment]
Is it possible to decide which entities are allowed on ships?
I am trying to limit the storage space on ships but having chest/hopper minecarts on a ship would nullify the restriction itself..

Would be nice to have an option to "whitelist" some entities :)

**Comment by cccm5** [comment]
It's not possible at the moment but it's something that is planned (actually someone is already working on it)

**Comment by Scarecrow-01** [comment]
Great!

**Comment by Jokkaj** [comment]
Also, I found a bug that involves rideable entities such as horses, boats and minecarts, you can't ride them on your craft while moving, when you are not riding them they move with the ship but when I ride them they just stay where they are, this is a problem because you can't use lifeboats to escape or you can't sit anywhere while moving the craft.

**Comment by eirikh1996** [comment]
Do you have onlyMovePlayers set to false?

**Comment by Jokkaj** [comment]
> 
> 
> Do you have onlyMovePlayers set to false?

yes, here I have the craft file, I am using the latest release

[Sloop.zip](https://github.com/eirikh1996/Movecraft/files/4480312/Sloop.zip)

**Comment by Jokkaj** [comment]
> 
> 
> Also, I found a bug that involves rideable entities such as horses, boats and minecarts, you can't ride them on your craft while moving, when you are not riding them they move with the ship but when I ride them they just stay where they are, this is a problem because you can't use lifeboats to escape or you can't sit anywhere while moving the craft.

should I create a separate issue for this?

**Comment by eirikh1996** [comment]
Does this only apply to mounted players?

**Comment by Jokkaj** [comment]
> Does this only apply to mounted players?

Entities have a similar problem, if you move a cow in a bot the cow will dismount, it won't stay in the boat.
Same thing for spider jockeys.

**Comment by cccm5** [comment]
The issue is on the api level. Teleportation via the api doesn't actually support teleporting things that are mounted/have mounts on bukkit/spigot/paper. It's going to have to be worked around.

**Comment by eirikh1996** [comment]
Atm, I am experimenting with a potential fix to this issue, and as @cccm5 states above, it is not possible to teleport entities mounted on a vehicle entity without having to first eject the passengers. I am looking into how I can remount the entities to the corresponding vehicle entities, but there is a chance that I have to leave the passenger entities dismounted

**Comment by eirikh1996** [comment]
Atm, I have found a solution to the problem, however, as one is solved, as usual, another occurs, which is that entities on vehicles teleport twice the distance the craft moves

**Comment by Jokkaj** [comment]
Did you fin a way to fix the issue?

**Comment by eirikh1996** [comment]
I did. Otherwise, this issue would remain open.

**Comment by Jokkaj** [comment]
> 
> 
> I did. Otherwise, this issue would remain open.

I have tried the new release, there is still a bug, if you ride an entity and then move your ship when you dismount you will be brought back at the coordinates where you mounted the entity.
For example, if I mount an horse and then I move my ship from point A to point B when I dismount I will be brought back to the point A
