### ISSUE TITLE
Can't Turn Ship More Than One Time

### ISSUE THREAD

**Issue by GalacticCraft** [eirikh1996/Movecraft#4]
**Describe the bug**
The ship cannot turn more than one time. If attempting to turn more than once, a message will appear in console from the second time and onward.
"[Movecraft] Cruising: false"
It will also change depending on whether cruise is turned on.
"[Movecraft] Cruising: true"

**To Reproduce**
1. Pilot the ship.
2. Attempt to turn the ship more than 1 time.
3. See error.

**Expected behavior**
The ship should continue to turn more than once if pressed more than once.

**Versions (please complete the following information):**
 - Movecraft: [e.g. 7.0.0 prerelease 9]
 - Java [e.g. JDK 8.0.2210.11]
 - Minecraft [e.g. 1.13.2]

**Additional context**
If you release the ship, it resets the turn so you're able to turn again. I don't want to have to release the ship every time I want to turn more than once.

**Comment by eirikh1996** [comment]
Fixed in the latest commit
