### ISSUE TITLE
Non-Block items are flooded on move.

### ISSUE THREAD

**Issue by Xyaren** [eirikh1996/Movecraft#40]
**Describe the bug**
Using an **airship**, on every move, every non-block item (fences,signs...) will be flooded with water.

**To Reproduce**
1. Create an airship with fences on it.
2. Take control and move a step
3. Observe flooding

**Versions (please complete the following information):**
 - Movecraft: Movecraft: v7.0.0_for_1.8.8-1.15.2_beta_18
 - Java 8
 - Minecraft 1.15.2

**Comment by Jokkaj** [comment]
> **Describe the bug**
> Using an **airship**, on every move, every non-block item (fences,signs...) will be flooded with water.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Create an airship with fences on it.
> 2. Take control and move a step
> 3. Observe flooding
> 
> **Versions (please complete the following information):**
> 
> * Movecraft: Movecraft: v7.0.0_for_1.8.8-1.15.2_beta_18
> * Java 8
> * Minecraft 1.15.2

Just update to beta 19 (the latest release)
