### ISSUE TITLE
Updated from Beta 13 to Beta 24 and Cruise is now super slow?

### ISSUE THREAD

**Issue by FrozenBeard** [eirikh1996/Movecraft#50]
Hello! 

On PirateCraft I updated from Beta 13 to Beta 24 and now Cruise is very slow, did the cruise variable name get changed for speed?

**Comment by eirikh1996** [comment]
cruiseSpeed is now actual meters per second, which means that it now takes cruiseSkipBlocks into consideration when calculating the cruise speed

**Comment by FrozenBeard** [comment]
So when calculating the speed of a ship, what variables do I need to set for cruise, and what is the maths for them to work? So i can figure out cruise speeds in crafts.
