### ISSUE TITLE
SubCraft Rotate somehow flys AND moves even when set to static/not flying.

### ISSUE THREAD

**Issue by FrozenBeard** [eirikh1996/Movecraft#53]
WoodTurret SubCraft: https://gist.github.com/FrozenBeard/c79795e6558b0f0c08cf02a0256f77a7

Video of a player able to FLY by rotating the craft around the rotate signs, no idea how on earth its flying, I have canFly: false and useGravity: true. allowHorizontalMovement: false and allowVerticalMovement: false
https://drive.google.com/file/d/1bjq3xqHXNourW-wUOfzu4yxBKHmj8Mbj/view

**Comment by eirikh1996** [comment]
One way to counteract this behaviour, you can use the maxSignsWithStrings flag

```yaml
maxSignsWithStrings:
   Subcraft rotate: 1
```

The issue you describes have been a part of Movecraft for a long time

**Comment by FrozenBeard** [comment]
Thanks @eirikh1996 what is the permission node to use SubCraft rotate signs for specific Crafts?

**Comment by FrozenBeard** [comment]
So this didn't fix it, as it rotates where the sign is, which means it can still be use as a flying machine!

Would adding Gravity or something fix it from flying?

**Comment by eirikh1996** [comment]
Typo in the flag. It is maxSignsWithString. For actual number, it must be prefixed by N

**Comment by TomLewis** [comment]
So I think people could just spam the helm sign and it would still rotate, therefor moving it in the sky.
I would love to get my SubCrafts back on for Turrets on ships and also for cranes etc, but they just need to not be flying...
