### ISSUE TITLE
Wrecks do not fade

### ISSUE THREAD

**Issue by TrollyLoki** [eirikh1996/Movecraft#54]
**Describe the bug**
Wrecked crafts never fade despite the FadeWrecksAfter setting

**To Reproduce**
1. Set FadeWrecksAfter to any number, for example 30.
2. Sink a craft
3. Wait 30 seconds (the number FadeWrecksAfter was set to)
4. The craft does not disappear

**Expected behavior**
After the configured number of seconds the wreckage of the craft should disappear

**Additional context**
This bug used to exist on both the main fork and this fork but it was fixed on the main fork and is still broken here.
Also just as a side note I think that the FadWrecksAfter value might be being treated as a milliseconds value instead of a seconds value.

**Comment by eirikh1996** [comment]
Does this exist in upstream too?

**Comment by TrollyLoki** [comment]
No, it used to but it was fixed since I last tested itOn Jun 18, 2020 5:04 PM, eirikh1996 <notifications@github.com> wrote:
Does this exist in upstream too?

**Comment by TrollyLoki** [comment]
No, it used to but it was fixed since I last tested it.
