### ISSUE TITLE
1.16.1 Torpedo etc Collisions bug?

### ISSUE THREAD

**Issue by bradyyykennyy** [eirikh1996/Movecraft#57]
Most recent version of movecraft for 1.16.1 seems to now have collision issues for Airships and Torpedos. I had not changed anything since the update but am now noticing regardless of collision settings, airships will only give warnings when approaching blocks no longer colliding, and torpedos when fired and they reach a block, will just stop moving and do nothing.

**Versions (please complete the following information):**
 - Movecraft: [e.g. 7.0.0 prerelease 6]
 - Java [e.g. JDK 8.0.1]
 - Minecraft [e.g. 1.16.1]

I really hope torpedos get looked at at least and Id like to know if it's just me for some reason or if there is actually a bug.

**Comment by duder123** [comment]
I've met the same issue regarding torpedos

**Comment by eirikh1996** [comment]
Fixed in 0ba3313308b5f1345cb14300a7a272971626cc48
