### ISSUE TITLE
Being able to transport certain mob types

### ISSUE THREAD

**Issue by UAVwaffle** [eirikh1996/Movecraft#61]
It would be really cool if you could transport mobs in some way.  My suggestion would be to make it so in the ships .craft file add a setting where you would add a list of mobs that the ship would transport. that would prevent the issue of if you are a ship fish and squid would get stuck to it, and would add the possibility to make a fishing vessel that would grab hold of fish as it drove past them, it would make villager tranport 10x easier, and finally make movecraft ALOT more useful.  as you can probably tell if this feature is possible I would HIGHLY recommend you add it.  thank you for your time in making this AMAZING plugin

**Comment by UAVwaffle** [comment]
UPDATE: looking at some craft setting files and some other bugs, I can't tell if the inability to move mobs is due to a bug or a lack of feature

**Comment by eirikh1996** [comment]
Set `onlyMovePlayers` in your .craft file to `false` and it will transport mobs

**Comment by UAVwaffle** [comment]
sweet thx
