### ISSUE TITLE
Fuel Types

### ISSUE THREAD

**Issue by TomLewis** [eirikh1996/Movecraft#65]
Hey Eirikh

With fuel, fuelBurnRate: 0.1 I have set in the craft files.

Is there anything else I need to get fuel to work?
My barge that requires fuel seems to work with no fuel.

I tried
```
FuelTypes:
    263: 5.0
    173: 10.0
```
In the main config.yml but this didnt change much.

**Comment by eirikh1996** [comment]
It is a per craft type setting now as of b30
