### ISSUE TITLE
passthroughBlocks not working

### ISSUE THREAD

**Issue by HightechCaveman** [eirikh1996/Movecraft#67]
**Describe the bug**
I have my passthroughBlocks set to pass through grass and flowers but it doesnt work

**Expected behavior**
Craft should pass through those blocks

**Screenshots**
https://i.gyazo.com/f86aae84caf673d9b468a88e1ab066d1.png
https://i.gyazo.com/d9f269ea9aab3feb4287fb61276fc811.png

**Versions (please complete the following information):**
 - Movecraft: latest
 - Minecraft: Server runs on 1.14.4, I'm on 1.15.2

**Comment by HightechCaveman** [comment]
It could entirely be me screwing up the config, but here is my vehicle file: https://pastebin.com/9FRCsiNC
Config: https://pastebin.com/ycvy3625

**Comment by GrandpaBlackTF2** [comment]
Solved the issue! Try making kelp all caps in your config, so instead of - kelp, it's - KELP
