### ISSUE TITLE
harvestBlocks: No Longer Works

### ISSUE THREAD

**Issue by GalacticCraft** [eirikh1996/Movecraft#7]
**Describe the bug**
The harvestBlocks: setting in the .craft files no longer work. When I attempt to move a ship through the blocks defined in the setting, the ship gets stuck on them instead of removing them and passing through.

**To Reproduce**
1. Pilot the ship.
2. Move the ship through a block that's defined for harvestBlocks: in the .craft file.
3. The ship won't move through the blocks.

**Expected behavior**
The ship should have removed the identified blocks and been allowed to pass through.

**Versions (please complete the following information):**
 - Movecraft: [e.g. 7.0.0 prerelease 9]
 - Java [e.g. JDK 8.0.2210.11]
 - Minecraft [e.g. 1.13.2]

**Additional context**
Here is the harvestBlock: setting from my .craft file. I tried to move the ship through the lily pad blocks.
[harvestBlock.txt](https://github.com/eirikh1996/Movecraft/files/3640329/harvestBlock.txt)

**Comment by eirikh1996** [comment]
You also need the harvesterBladeBlocks too. Do you have that in the .craft file?

**Comment by GalacticCraft** [comment]
I do not. I was unaware that existed. Would it just look like harvesterBladeBlocks: with the same layout?

**Comment by eirikh1996** [comment]
Yes. It would
