### ISSUE TITLE
Pilot signs not working

### ISSUE THREAD

**Issue by HightechCaveman** [eirikh1996/Movecraft#73]
**Describe the bug**
Whenever a player puts a pilot sign on a ship, others can still pilot it. This is only for some ships, pilot signs work and dont work depending on the craft.

I have pilot signs enabled, piloted crafts are protected, anyone can create them, they just work half the time.

**Comment by eirikh1996** [comment]
Fixed in 62909fdb722294aaad3593fc38839c8901f75c11
