### ISSUE TITLE
Torpedo not exploding

### ISSUE THREAD

**Issue by UAVwaffle** [eirikh1996/Movecraft#82]
Whenever I launch a torpedo and it hits it's target, it does not explode.  When I try to break the coal blocks it's says (not exact) "this block is part of craft".

I get the following error in my servers console when it hits the block 
26.09 16:46:04 [Server] ERROR Async task generated an exception
26.09 16:46:04 [Server] WARN java.lang.IllegalStateException: CraftReleaseEvent may only be triggered synchronously.
26.09 16:46:04 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595)
26.09 16:46:04 [Server] WARN at net.countercraft.movecraft.craft.CraftManager.removeCraft(CraftManager.java:170)
26.09 16:46:04 [Server] WARN at net.countercraft.movecraft.async.translation.TranslationTask.execute(TranslationTask.java:450)
26.09 16:46:04 [Server] WARN at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:45)
26.09 16:46:04 [Server] WARN at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
26.09 16:46:04 [Server] WARN at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
26.09 16:46:04 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
26.09 16:46:04 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
26.09 16:46:04 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
26.09 16:46:04 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)

Also it will stop 1 block before hitting the object unless the object is coal.

and finally I have a question,  How do I increase the torpedo's firing range and what does "focused explosion" mean.

If you need more info feel free to ask and thank you for this extraordinary plugin!

Here is my .craft file

name: LaunchTorpedo
maxSize: 7
minSize: 1
allowedBlocks: 
- COAL_BLOCK

forbiddenBlocks:
    - BEDROCK

canCruise: true
cruiseOnPilot: true
focusedExplosion: true
mustBeSubcraft: true
cruiseSkipBlocks: 1
canFly: false
minHeightLimit: 65
maxHeightLimit: 65
detectionMultiplier: 40.0
underwaterDetectionMultiplier: 4.0
collisionExplosion: 3.0
explodeOnCrash: 3.0
moveEntities: false
speed: 9.0
tryNudge: false
sinkPercent: 99.0
overallSinkPercent: 99.0
passthroughBlocks:
- KELP
- KELP_PLANT
- TALL_SEAGRASS
- SEAGRASS
- BUBBLE_COLUMN
flyblocks:
    COAL_BLOCK:
        - 10.0
        - 100.0

**Comment by ninest** [comment]
I'm having the same issue with torpedos. I can launch them, but they just hit a block and stay there, no explosion. I get the same logs as you.

From the [Type File](https://github.com/APDevTeam/Movecraft/wiki/Type-File) docs:
> focusedExplosion (Boolean): Determines if an explosion based craft should have explosions occur distributed throughout the craft or only at the point of contact

**Comment by UAVwaffle** [comment]
I hope they fix this soon, I need torpedo's :(

**Comment by eirikh1996** [comment]
What version did you test on?

**Comment by UAVwaffle** [comment]
1.16.1 latest release

**Comment by UAVwaffle** [comment]
update my server to 1.16.4 and plugin to 35, the bug is still found

**Comment by UAVwaffle** [comment]
UPDATE: VERSION 36 HAS FIXED IT
