### ISSUE TITLE
How to Install Combat Addon

### ISSUE THREAD

**Issue by Grievous07** [eirikh1996/Movecraft#86]
Sorry noob here. Just confused by how to install the combat addon. Even read the README I opened from the WinRAR (my server files are in FTP on a website hosted by pebblehost) but ya, sorry just don't understand. Could someone help, please?

**Comment by TylerS1066** [comment]
Head over to [my post on SpigotMC](https://www.spigotmc.org/resources/movecraft-combat.81574/) to download the latest jar and plop it in your plugins folder.  By default it should be configured to exactly replace the features removed from Movecraft.

**Comment by Grievous07** [comment]
Ya, then in assets I download the "Source code (zip) " and open it in winRAR. Then I can't find which file in it is the exact plugin.yml for the server

**Comment by TylerS1066** [comment]
Woops!  I forgot to attach the jar to the release.  [This should be a direct link to download the jar](https://github.com/TylerS1066/Movecraft-Combat/releases/download/v1.0.3/Movecraft-Combat-1.0.3.jar).

**Comment by Grievous07** [comment]
Sweet! Thanks : )
